### ISSUE TITLE
[Community Review] NUM token rewards and utilities

### ISSUE THREAD

**Issue by ethanwu155** [numbersprotocol/community-support#1]
**Topic**: [NUM Token Rewards & Utilities](https://github.com/numbersprotocol/community-support/wiki/%5BUnder-Community-Review%5D-NUM-token-rewards-and-utilities)
**Review Period**: 17th Nov - 16th Dec
**Status**: Open

**Overview**: NUM Token Rewards & Utility is a detailed overview of the different rewards structures in the Numbers Protocol Decentralized Photo Network. This wiki will cover topics such as staking, Integrity Rewards, Verification Rewards, Governance and CAPTCH-A. 

**How to Review:** Leave a comment. Please follow rules and guidelines outlined in [Rules for Community Review](https://github.com/numbersprotocol/community-support/wiki/7.-Governance)

**Comment by Mariolino19** [comment]
hi, I am writing because in recent days I encountered a problem in purchasing token numbers. In particular, I invested through the poocoin platform, and due to liquidity problems, of 2000 dollars invested now I find myself 0.4

**Comment by Sudhakar111288** [comment]
Hi Team 
Staking 2000 NUM for activation of existing CAPTCH-A (Gray) look high. If Team reduce Staking amount for CAPTCH-A holders we really feel lucky 

I hope Team will consider our request

**Comment by Mariolino19** [comment]
I have another tupy of problem, please check my request

**Comment by ethanwu155** [comment]
@Sudhakar111288 thanks for the comment. we will definitely take your point into consideration :) What do you think would a reasonable of NUM to stake?

**Comment by ethanwu155** [comment]
@Mariolino19 this thread is to discuss topics related to products in particular `Community Review` of the _NUM Token Rewards & Utility_ document. Any token related questions should be directed to appropriate channels in TG or Discord.

**Comment by Sudhakar111288** [comment]
@ethanwu155  
thanks for considering my request.  It will be good if team make it as 1000 NUM.

**Comment by ethanwu155** [comment]
@Sudhakar111288 great! thanks for the feedback. let me share with the team and we'll drop our thoughts on the matter :) anything else in the doc that your think is interesting or needs more expanded details?

**Comment by iamBishalChakraborty** [comment]
Date: 24/10/2021
NUM & BUSD LP Farming open! (Staking mentioned on the [post](https://t.me/numbersprotocol/65150), actually, it is lp farming )
Farming has 2 types: LP farm and staking farm.
**Staking** is token per token you get some % of the fee and the rewards only per this token you chose.
**Lp farming** will be for a pair of tokens - so the lp token you will get by adding liquidity that will generate the lp token you are staking on in the LP farm.
We, Holders also demand staking! Hope soon to see it

**Comment by ethanwu155** [comment]
from discord by @imonlydan

```
I was wondering how the app could grow and I came up with a suggestion, unless I missed it, would it be possible to add some type of refer a friend to the app feature, doesn’t have to be like a token dump but I feel like it would help reach more people and get more people engaged with the app. Something like refer 2 friends get 1 waived mint fee, something along those lines.
```

**Comment by imonlydan** [comment]
@ethanwu155 I see that you were talking about the requirements of obtaining a CAPTCH-A NFT. I'd like to add an alternative suggestion, if made to be a set amount, and price of NUM inflates, many community members that aren't financially able won't be able to get one. I feel like maybe the first tier at least should be set at a price, I'm going to reference a S-Coin called Catgirl. They have a "mystery box" that always stays at the equivalent of about 10USD by changing the amount of CGC needed to buy one mystery box as market changes. This could maybe be done to at least the first tier, it would be hard to implement something like this with staking though I haven't thought it through that far but hey just launching ideas that may suit the community better.

**Comment by ethanwu155** [comment]
@imonlydan that's a good observation. I think you are right that as the value of NUM inflates we don't want staking and the subsequent community network actions (verification reward, governance, CAPTCH-A) to be feel "exclusive" as the Numbers network wishes to be inclusive.

**Comment by imonlydan** [comment]
A different approach to earning the first tier of CAPTCHA-NFT (first tier only) could be making a separate tier list in app, tying back to the "refer a friend" idea, there could be a set amount of tiers proving your a proactive member of the community. Referring friends, participating in 1 or two "challenges", Minting 3 pictures ETC. Could all help you reach the first tier of CAPTCHA, thus removing the financial aspect while maintaining the "Demonstrating you are an active member in order to receive a ticket for a specific governance call" mentioned in the paper.

**Comment by ethanwu155** [comment]
@imonlydan i like the idea. It's almost like gamification (similar to daily tasks in mobile games). I this idea is something we can definitely consider!

**Comment by 43z708** [comment]
I expressed the following opinions in telegram, but as a member of the Numbers community, I would like to make a suggestion here.

Premise
According to the white paper, rewards such as Integrity reward and Verification reward are indeed weapons to grow the product and community, but they are also potential selling pressure.
I believe that the value of $NUM will naturally increase as the product grows, but a system that maintains a balance between buying and selling pressure is essential for the growth of the community ecosystem, and we should build a system that encourages healthy growth in the price of $NUM.
Burning tokens has the effect of increasing scarcity value, but I think it should be considered separately from buying pressure.


So I have two suggestions.
1. how about having $NUM pay for the enterprise usage of numprotocol api?
Part of the $NUM purchased by the enterprise will be burned, and part will be used to generate revenue for the operation.


2. captureclub currently allows users to purchase in ETH or USD, but we will make it possible to use $NUM.
And make the fee a little higher for ETH and USD, and lower for $NUM.
I think this will create pressure to buy $NUM in order to buy NFT.
And the above two suggestions are tied to maintaining a healthy price for $NUM, since the mechanism is to increase the pressure to buy $NUM as the numbersprotocol ecosystem grows.


Thanks for the opportunity to make suggestions.

**Comment by nanjiponyo** [comment]
Hello, can I ask technical questions about the vulnerabilities of your "system"?
1. How do you manage not to allow the smart contract (which is used to publish images just taken by the application) from being used by other people "maliciously" to publish images not taken by your app?

2. There is no blocking on the use of virtual cameras. I can pass off a fake image taken by your app as real.

3. The images, in addition to being saved locally on the device, are they saved in centralized servers? View the "backup" function.

4. Since (ionic) the app uses a (capacitor) plugin that uses the default camera of the phone, what does not allow me to change the default camera, in order to use cameras that allow you to take pictures as well as upload images from the gallery? I could upload images where the metadata has been spoofed and the images themselves have been spoofed.

**Comment by tammyyang** [comment]
@43z708 Thank you for bringing the discussion here. I am sure Github is a better and more open space for deeper discussion :).
Regarding the suggestions

> 
>     1. how about having $NUM pay for the enterprise usage of numprotocol api?
>        Part of the $NUM purchased by the enterprise will be burned, and part will be used to generate revenue for the operation.

The aligns with the current plan. I believe it makes sense for users of Numbers technology to pay NUM instead of fiat. The challenge will be, enterprises need estimable costs to run a sustainable business. The big fluctuation of crypto may become the barrier to stop them from using Numbers Protocol.

The current idea is to create a NUM fund. When the price goes high, the fund may liquidate some NUM tokens, and when the price goes low, this fund can be used to create incentives for enterprise users or help them use Numbers API with a relatively stable price. These are just some super preliminary ideas, nothing serious yet. Any suggestions/comments are more than welcome. 

>     2. captureclub currently allows users to purchase in ETH or USD, but we will make it possible to use $NUM.
>        And make the fee a little higher for ETH and USD, and lower for $NUM.
>        I think this will create pressure to buy $NUM in order to buy NFT.
>        And the above two suggestions are tied to maintaining a healthy price for $NUM, since the mechanism is to increase the pressure to buy $NUM as the numbersprotocol ecosystem grows.

We have been working on NUM payment already. Probably the better way to encourage users to pay with NUM is to create incentives, such as 10% off if you pay with $NUM. I know it may sound the same as a higher fee in ETH and USD, but encouragement instead of punishment is usually a better solution I think.

> 
> Thanks for the opportunity to make suggestions.

Appreciate your suggestions! This community repository will always be open. Please feel free to join discussions for a specific topic, or open a new topic if it does not exist yet.

**Comment by 43z708** [comment]
@tammyyang Thanks for your reply.
The Japanese community has also been talking about the excellent response of Numbers' management team.

>The current idea is to create a NUM fund. When the price goes high, the fund may liquidate some NUM tokens, and when the price goes low, this fund can be used to create incentives for enterprise users or help them use Numbers API with a relatively stable price. These are just some super preliminary ideas, nothing serious yet. Any suggestions/comments are more than welcome.

Great idea.
Given the potential of numprotocol's business, I believe that the price of $num has the potential to rise beyond imagination.
At that time, I think it would be contrary to the original purpose of the fund to try to control the price increase.

If you like, you can also consider the following two methods:

1. use the $num price reference oracle. In other words, collect the num corresponding to the dollar-based price determined for each transaction.

2. collect api usage fees in dollars, and immediately convert the dollars into $num at the backend. In other words, buyback by the operation.

>We have been working on NUM payment already. Probably the better way to encourage users to pay with NUM is to create incentives, such as 10% off if you pay with $NUM. I know it may sound the same as a higher fee in ETH and USD, but encouragement instead of punishment is usually a better solution I think.

I am genuinely wondering if the 10% off price is not a disadvantage to the seller?

**Comment by tammyyang** [comment]
@43z708 

Regarding the question "if the 10% off price is not a disadvantage to the seller" , here are my opinions

As "trust" has its value (thinking about when we buy things on Amazon, we tend to buy items with high review scores even though these items are sometimes more expensive), I believe sellers can sell the items at a bit higher price than on other platforms. I.e. theoretically, buyers are willing to pay a bit higher price for this "guarantee". This gives us some room to compensate users who use NUM to trade because they participate in the building of Numbers Protocol by using its default currency.

Regarding how to provide a stable price for enterprises, I think we will not know the answer until we get more feedback from the customers. Let's keep the discussion open for now; I am sure there will be a better answer later.

**Comment by 43z708** [comment]
@tammyyang 

Thanks for your reply.
It seems to me that with this system, sellers will set their prices based on the price in $NUM, and most buyers will trade in $NUM. This is going to contribute to the growth of the ecosystem.

I will continue to support numprotocol, so if there is anything we as a community can do to help, please ask us.
If I come up with an idea that can help numprotocol move forward, I'll suggest something else.

**Comment by ethanwu155** [comment]
@nnnanji Thanks for sharing your thoughts and questions. 

```
How do you manage not to allow the smart contract (which is used to publish images just taken by the application) from being used by other people "maliciously" to publish images not taken by your app?
```

Every photo taken with Capture APP is signed digitally and embedded into the asset itself via metadata injections (based on official C2PA standards). The Numbers Network will leverage these digital signatures and metadata injections to certify that the asset was created by the creator. The mechanism described here is applied to all assets we certify (including assets from partnerships). 

The smart contract issue that you bring up is an interesting one. Since smart contracts are separate from the Numbers Network, there isn't much we can do to prevent them from utilizing/published images without permission. This issue is tied to the entire web ecosystem. Because the current web ecosystem (including Web3.0) doesn't have much in the way of preventing unpermissioned usage ("right click & save phenomenon") its difficult to prevent the scenario that you described.

What can be done though is having metadata injections such as the ones that are present in every Capture. Metadata injections make it possible for assets to be verified easily (by the community) because the asset itself can speak for itself. We can also leverage metadata injections within our Numbers ecosystem to have permissioned usage. 

Consider the following scenario:

I want to upload a profile picture in the Numbers Network. The network would read the photos injected information (metadata) to confirm that I am the creator (cross-check signature with wallet address) to confirm that I am the creator or owner of the photo, before granting me the privilege to use it.

Another key aspect of keeping assets infringement and violations low is leveraging the community via community verification or social proof. The [NUM Token rewards and utilities](https://github.com/numbersprotocol/community-support/wiki/%5BUnder-Community-Review%5D-NUM-token-rewards-and-utilities) document on GitHub goes over this more in detail. Highly recommend you check it out and let us know your thoughts. 

You can also check out this [Medium](https://medium.com/numbers-protocol/how-to-claim-copyright-with-numbers-protocol-c114e497f574) to see an example of permissioned usage within Numbers network.

**Comment by ethanwu155** [comment]
@nnnanji 

```
There is no blocking on the use of virtual cameras. I can pass off a fake image taken by your app as real.
```

We are aware of this potential issue and its part of our roadmap. Thanks for pointing it out :)

**Comment by ethanwu155** [comment]
@nnnanji 
```
The images, in addition to being saved locally on the device, are they saved in centralized servers? View the "backup" function.
```

Yes. There is a backup image stored on the backend. This is for providing faster access to files and improving user experience. When users chose to de-register photos, the backup image on the backend will also be deleted.

**Comment by ethanwu155** [comment]
@nnnanji 
```
Since (ionic) the app uses a (capacitor) plugin that uses the default camera of the phone, what does not allow me to change the default camera, in order to use cameras that allow you to take pictures as well as upload images from the gallery? I could upload images where the metadata has been spoofed and the images themselves have been spoofed.
```

We chose to use ionic because we believe bring the same user experience on iOS and Android is important. That said, we are aware of some of the limitations of the framework. Our initial feedback tells us that Capture APP as it is (with its current camera functions) is suitable for most common usage. If we receive more feedback requesting for more camera options, which cannot be satisfied by Ionic framework, than we may consider rebuilding Capture APP as a native app.

FYI: The Pro version of Capture APP (utilized by Reuters photographers in 78 Days) was built with Kotlin so if the demand is present, we can go the native route to provide more camera options for our users.

In terms of uploading images from gallery, we do not allow upload onto Capture APP because we cannot guarantee that these photos are created by the uploader. Assets created with Capture APP have the highest level of verification in the Numbers Network because of the current design (no uploads). Currently if users want to upload a creation they will need to do so with CaptureClub via Creator Gallery function. 

Creator Gallery allows users to upload photos, videos to create Captures, generated blockchain certificate, inject metadata, mint NFT and list in CaptureClub. NOTE: assets created this way have lower verification level.

Capture APP uploading is a feature that many people are requesting. For this reason we will be removing this limitation after we implement the feature to classify photos to different integrity levels.

**Comment by tammyyang** [comment]
@43z708 

> It seems to me that with this system, sellers will set their prices based on the price in $NUM, and most buyers will trade in $NUM. 

Yes, that's correct.
Thank you for the feedback! We are going to have developer bounty and ambassador programs soon. Or, if you have any suggestions on how to bring the community into the project and build together, please let us know. Community involvement is super important!

**Comment by 43z708** [comment]
@tammyyang 
I'm very interested in developer rewards.
I wonder what kind of content it is.
In the meantime, I'll have a look at the source code of capture-lite when I'm free.
I'm looking forward to it!

**Comment by 43z708** [comment]
@tammyyang 
Thanks for the valuable info!
I'm very interested in developer rewards, so I'll read the source code of capture-lite in my spare time anyway.
If there's anything useful that we should prepare, I'd appreciate it if you could tell us as much as you can.
Thanks again!

**Comment by nnnanji** [comment]
Hi everyone!
Why are there no NUM/BUSD, NUM/ETH, NUM/BTC pairs on exchanges? I want to know the reason :)
