### ISSUE TITLE
Security Issue - DMARC Setup

### ISSUE THREAD

**Issue by willcoursen** [numbersprotocol/community-support#10]
Any VC, angel or principle driven investors will look this up to understand how serious you are about security. Could raise lots of necessary red flags. I called this out early this week and you fixed it. So much appreciated just wanted to make sure y'all are tracking my support. 
![DMARC Status](https://user-images.githubusercontent.com/17142178/146579267-13b65556-e3ef-4ee8-867f-07405d1201b6.jpg)

**Comment by tammyyang** [comment]
![photo_2021-12-21_23-36-25](https://user-images.githubusercontent.com/5687908/146956935-de902794-96c8-4e95-b42a-29479fb6443f.jpg)

Thank you for pointing this out.
Also added the fixed result.

The yellow mark is because we followed the default instruction and leverage the not-too-aggressive setting for now.
