### ISSUE TITLE
Discussions and Suggestions for a New Phase of Ambassador Program Tier 1 

### ISSUE THREAD

**Issue by Charles7021** [numbersprotocol/community-support#116]
### **A New Phase of Ambassador Program Tier 1**

As Ambassador Tier 1 has helped a lot of new members get familiar with the Numbers project (and some of them have even become Tier 2 ambassadors), let's gather some feedbacks to improve and optimize the current Tier 1 rules.

We have 4 kinds of task right now:

```
A: Twitter Shilling
B: Super Hero Polling in Telegram
C: Translation
D: Virtual Contents
```

Let's be constructive, specific and pragmatic. State to which task you are providing suggestions, for example:

```
For Task A:

I wish we could allow more shillings to be rewarded for the week. 
The reason is that ... 
To do it, we might need ...
```

or

```
I want a new Task type:

I wish we should have Capture contest every month. 
The reason is that ... 
To do it, we might need ...
```

or

```
Besides from the tasks:

I wish we could ...
The reason is that ... 
To do it, we might need ...
```

The main point is to make people from knowing only a little about Numbers to ones caring about Numbers. Most important of all is that we make it simple, fair, not too difficult and full of love.

We appreciate all the feedbacks from people who care about Numbers! The team reserves the rights on the final decisions regarding related topics.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248715554875) by [Unito](https://www.unito.io)

**Comment by Enjoybro** [comment]
I want a new Task type:

I wish we should have Capture contest every month. 
The reason is that ... 
To do it, we might need ...

**Comment by CihanTuran92** [comment]
Photo Contest everyweek for CaptureApp would be nice. We can make a poll on Twitter & Telegram to vote which ones are the best. We need more users & activities on CaptureApp.

**Comment by Cryptoguy86** [comment]
First of all, I don't know what is,.. or how much the team has access to build or change what is inside the Numberverse show room.

"what is the limit"
 
Tier 1

task A: Twitter shilling
task B: super hero
Task C: Translation

beside from the tasks, we can add on each tasks what's follow:

the winner names will be in the Numberverse wall with their achievements it will be updated weekly.

example:

Task A: Twitter:
 The winner's name will be on the dashboard wall in Numberverse with how many posts he did plus how many likes he got, and there will be records for those who won will show how many posts and likes, and members will be challenging each other to break that record as a motivation.

by that we are using Numberverse and increasing the enter flow to Numberverse,

Task B: super hero will be named on the dash board in Numberverse.

Task C: Translators, names will be in the dashboard in numberverse with their details regarding their work.


Task D: Virtual Contents

Such Capture app, members will be taking photos and they are able to choose one photo from his/her album to send it for the contest to allow the other members to vote for the best 4 photos or "you decide how many" among all other photos and the highest voted photo among the 12 months will get the biggest reward. to keep members to participate in each month to get more votes. 

and its monthly campaign, and these photos will be hung on Numberverse walls and with rewards from high to low respectively
note: the photo must have the month dated on the photo the same as the campaign month.


the reason of that to involve our metaverse and increasing the flow to numberverse and increasing the shilling motivation between the members to see their names in the metaverse and to show it between each other, and the most important to allow the members to use the numberverse for future meetings and interaction
and as we noticed there is a lot of members are not active, you will find them active only where is rewards and behind the scene.

all that just an idea, able to polish it or fix it or to improve it.

**Comment by AniaBeg** [comment]
First of all, as mentioned, Capture Contest would be really engaging. Since people like posting and sharing photos, it could be a theme Twitter contest each week or month.  As it would be on Twitter, more people could see it, get interested and take part. 

I also think that people are competitive by nature and as Numbers gathers a worldwide community, it could be nice to create contests showing typical places/dishes for each country (first stage of the contest), then one of the photos from each country could pass to stage two and one photo could win in the end. I think people could get involved in voting and sharing the photo from "their country". Maybe also the contest "Guess where was that Capture taken" or something similar could work. 

I also think that there could be more  short YT videos/tutorials showing how to use marketplace or even the Capture app. I know it is very basic, but from my experience, people like to see something rather than figuring it out themselves.

If there are translated parts of the articles, it would be nice to collect them in one section, on blog or medium as a section with foreign translations, so everyone could easily find it ( I think it would be easier to find than on Github)

More events in Numberverse, which could be connected to the contests (maybe announcing the winner during the event by showing the winners photo) or in a different way (the ideas mentioned by  others - showing the photos in Numberverse seems great)

**Comment by ethanwu155** [comment]
Thank you for all the responses from the community. We appreciate your interest and feedback for the Ambassador Program. Given this discussion was initiated more than 2 years ago, we will be closing this topic. If you have any issues or feedback to provide don't hesitate to do so. Thank you!
