### ISSUE TITLE
Dappradar, Coingecko, & Coinmarketcap should have the same info about circulating supply.

### ISSUE THREAD

**Issue by sicnarf9999** [numbersprotocol/community-support#173]
Please ask those platforms to have a unified info about NUM. 
I believe you just have to send them an email of request to update the info of NUM on their platforms

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203424117722084) by [Unito](https://www.unito.io)

**Comment by scott-dt** [comment]
Hi sicnarf9999,

Thank you for your suggestion. To implement a system where users who burn their tokens are recognized, we would need to collect and disclose personal information such as email addresses, Capture account details, and wallet addresses. This could expose users to potential risks, including targeting by malicious entities and unwanted attention. Privacy and anonymity are highly valued in the cryptocurrency industry, and we strive to uphold these principles.

Additionally, we have already made significant changes to the NUM burn mechanism since 2023. We now burn at least 6M NUM per quarter to ensure a controlled and effective reduction in token supply.

If you have any further feedback on the burn rate or other aspects of our protocol, please feel free to share your thoughts with us.
