### ISSUE TITLE
Prioritize getting listed on other decentralized exchanges

### ISSUE THREAD

**Issue by sicnarf9999** [numbersprotocol/community-support#174]
UNIswap and Pancakeswap are not enough, we need mo DEX listing.
The more DEX we have, the more VOLUME we will get.
This should be on the roadmap for 2023

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203424063494625) by [Unito](https://www.unito.io)

**Comment by scott-dt** [comment]
Hi sicnarf9999,

Thank you for your input. We understand the importance of having our token listed on multiple decentralized exchanges (DEXs) to increase trading volume and accessibility. However, listing on too many DEXs could impact token liquidity and potentially harm the trading experience due to low liquidity on some platforms.

As of 2024, we have listings on Uniswap for USDC pairing (Ethereum chain) and PancakeSwap V3 for USDT pairing (BSC). Both DEXs have a good amount of liquidity and should provide users with a great trading experience. Additionally, we now have new listings on top centralized exchanges (CEXs), including Crypto.com and HTX.

We will continue to evaluate and consider additional DEX listings strategically to ensure they align with our goals and benefit our community.

Thank you again for your suggestion.
