### ISSUE TITLE
Voluntary burning of NUM coins

### ISSUE THREAD

**Issue by sicnarf9999** [numbersprotocol/community-support#175]
There should be a voluntary burning of coins, but in return, people who burnt their coins voluntarily should be recognized as "heroes"

Like their names or usernames should be posted on the website or in the blockchain, or something like their photos in the Capture app should be on the top of the list.

Expectation flow
User who owns NUM token could burn it by themselves, and it could have some badge on capture service.

This feature will include NUM, protocol, and capture app

User story
As a NUM token owner, I could burn the NUM token which I own by myself, so that I could have badge on the NUM community or capture service.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203423991653381) by [Unito](https://www.unito.io)

**Comment by scott-dt** [comment]
Hi sicnarf9999,

Thank you for your suggestion. To implement a system where users who burn their tokens are recognized, we would need to collect and disclose personal information such as email addresses, Capture account details, and wallet addresses. This could expose users to potential risks, including targeting by malicious entities and unwanted attention. Privacy and anonymity are highly valued in the cryptocurrency industry, and we strive to uphold these principles.

Additionally, we have already made significant changes to the NUM burn mechanism since 2023. We now burn at least 6M NUM per quarter to ensure a controlled and effective reduction in token supply.

If you have any further feedback on the burn rate or other aspects of our protocol, please feel free to share your thoughts with us.
