### ISSUE TITLE
Numbers goes DID - feature proposal 

### ISSUE THREAD

**Issue by ChrisSvensson** [numbersprotocol/community-support#18]
The possibility with Numbers protocol to take on decentralized ID

Unique fingerprint of your ID, stored in a secure way.

examples of use case:
- Digitalt Passport - Possibility to scan you Decentralized ID through your phone. Never have to use a physical passport that can be lost. 
- Prevent identity theft 
- Identify your crypto accounts (instead of keys that can be used by many)

There are numerous ways where an identification is needed in both the digital and physical world, but where the lack of security make it possible for theft and misuse of others identification. 

NFT - will secure the identification of the one person it belongs to

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248722820746) by [Unito](https://www.unito.io)

**Comment by ChrisSvensson** [comment]
Recruit me and I will connect the numbers protocol with a Blockchain that is accepted buy gouvernments all over the world and the passport of the feature will take place

**Comment by ethanwu155** [comment]
Thank you for taking the time to share your feature proposal. While a decentralized ID is very interesting, Numbers Protocol project works to register and index digital media with unique Numbers ID and create on-chain provenance records to make them traceable and verifiable. Unfortunately a decentralized ID for passports and identification falls outside the scope of what we do. However since its an interesting ideal, we have noted your proposal and if there is any changes in direction we will revist this topic. Appreciate your time and let us know if you have any other ideas.
