### ISSUE TITLE
Errors after use of "add password later"

### ISSUE THREAD

**Issue by web2hotel** [numbersprotocol/community-support#19]
On signup the new user can opt for "add password later" with no more messages.

1. Go to 'login'
2. Click on 'signup'
3. The checkbox "Set my password later" is present
and no other instruction is written in the profile page. At a later attempt to complete the signup normally the user input the same email and the password but get the error of email already registered. That's confusing: The only way to complete the signup with password is clicking forgot-password.

**Expected behavior**
At a later attempt to complete the signup the system should accept the the password (1st time given for association with that email).

**label**
CaptureClub

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248801262187) by [Unito](https://www.unito.io)

**Comment by KNctrl-alt** [comment]
I agree that Capture Club/Capture App require some upgradation with respect to the process of onboarding new users and the interface. 

Having said that, I don't think this addresses the issue properly, since you were basically signing up twice for the capture club, resulting in the clash of email entries. In other words, signing up was completed the moment you clicked on signup the first time.

I think the issue here should be _the absence of a way to set password later after signing into Capture Club_ instead of going through that "Reset password" route. Apparently, that is where the confusion is, as people after checking the "set password later" box would expect to sign in and find the settings (or a similar) tab where they can make those changes.

**Comment by kennyhungQA** [comment]
CaptureClub is no longer supported. We welcome you to continue experiencing the seamless Web3 experience provided by Numbers Protocolo through [Capture Dashboard](https://dashboard.captureapp.xyz/). Close this issue.
