### ISSUE TITLE
Allow the picture to be organized in folders.

### ISSUE THREAD

**Issue by AKT4UnMe** [numbersprotocol/community-support#20]
**Is your feature request related to a problem? Please describe.**

**Describe the your user story**
Share your user story. If you are not clear about what user story is, please take a look of https://en.wikipedia.org/wiki/User_story

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Select label**
Based on the issue category, please select a label from General/Capture App/NFT Search Engine/CaptureClub

**Additional context**

**Comment by ethanwu155** [comment]
@AKT4UnMe do you think you can elaborate a bit on what you want to see with this feature request. I noticed that the questions in the template are unanswered >.<

it would be very helpful for us to understand if you provide more details. Thanks!

**Comment by KNctrl-alt** [comment]
@AKT4UnMe Hello friend, I thought there could be a simpler solution of organising captures by adding tags to those captures, which can be used later for grouping captures with the same tags together in the same window. (without having to navigate to different locations/directories/folders). I have opened a new feature request at #22 for that purpose.

**Comment by AKT4UnMe** [comment]
I apologize for my laconic prose.

Here are my extended thoughts.

Is your feature request related to a problem? Please describe. It would be helpful to be able to save images in folders. When Listing pictures on the Market place they are in order of the time listed, but as a photographer who is shooting different subjects, it would be nice to be able to organize images in folders, or at least separate lists. Example, here is my Sunsets folder (or portfolio), here is my flowers portfolio. It will clean up the experience and photographs presentation. 

This could apply to in-app too (not just the Market place). I’ve made hundreds of pictures so far and it is difficult to find an image I made weeks ago.

Describe the your user story
To date I have enjoyed the app. It is reasonably simple to use when taking pictures. I take a lot of images of multiple different subjects, which is why a better organization system would be appreciated (Even if there was a keyword search function).

Aside from wanting an easy image organization function, I like to see some, at least basic, editing functions (Cropping, exposure adjustments, etc). 

Also, and this may be a separate issue, market place (captureclub.cc) is clunky with its single column row of images. I can’t search for subjects, photographers, etc. because it is one endless list. When I log into my profile, I cannot tell (without excessive scrolling and multiple clicks) which images I’ve listed and which are not. 

Describe the solution you'd 
It would be great to able to assign my images to different folders (or portfolios) by subject or by keywords. Similar to “albums” in an iPhone photo roll or folders like the iCloud Drive. 

This would allow me an an artist to keep like images with like images instead of having a folder with a dog, a sunset, a basketball, and an omelette. With folders/portfolios, I can present my animals portfolio, my sports portfolio, and my food portfolio separately. This would also make it easier to search for the pictures I took because if I made a picture of a dog in June and I want to look at it in December, instead of endless scrolling, I can go to my animal portfolio and search amongst a smaller image list. (Allow user to add keywords would make this even easier.)

When I share on CaptureClub.cc, my profile won’t be a list of random pictures, instead it would have a cleaner  presentation. 

Also, by separating into portfolios, I can have a series of NFTs that are 1/1 and another series that is 5/5 or 100/100 and adjust prices accordingly, creating a tiered price structure.


Describe alternatives you've considered It terms of other apps, I don’t know of any alternatives. Capture App is pretty unique but the other apps that I use that have functions I’d like to see implemented would include editing functions like Snapseed, organizing functions like LightRoom mobile, and presentation functions like OpenSea or some of the other NFT sales platforms for CaptureClub.cc


Select label General/Capture App/CaptureClub


Additional context

**Comment by ethanwu155** [comment]
@AKT4UnMe We have taken your feedback regarding "Portfolios" in CaptureClub and implemented a few feature changes. See the following rundown for more information.

"It would be great to able to assign my images to different folders (or portfolios) by subject or by keywords. Similar to “albums” in an iPhone photo roll or folders like the iCloud Drive.

This would allow me an an artist to keep like images with like images instead of having a folder with a dog, a sunset, a basketball, and an omelette. With folders/portfolios, I can present my animals portfolio, my sports portfolio, and my food portfolio separately. This would also make it easier to search for the pictures I took because if I made a picture of a dog in June and I want to look at it in December, instead of endless scrolling, I can go to my animal portfolio and search amongst a smaller image list. (Allow user to add keywords would make this even easier.)

When I share on CaptureClub.cc, my profile won’t be a list of random pictures, instead it would have a cleaner presentation."

We interpreted the above feedback in the following way:

1) Have a way to categorize Captures for better organization (tagging)
2) Have a way to search for pictures so that user does not need to scroll down a long list of Captures (filtering in About / Custom Marketplace)
3) Have a way to showcase specific categories of Capture NFT in CaptureClub (Custom Marketplace)
4) Have a way to share specific portfolio to prospective customers (Shareable Link)

See the following demos for more details

**Comment by ethanwu155** [comment]
**Tagging**:

All Capture NFTs in CaptureClub can have up to 3 tags. These tags are showcased in the `Product Details` Page under the NFT preview image.

<img width="1280" alt="Screen Shot 2022-02-22 at 12 18 43 AM" src="https://user-images.githubusercontent.com/17772957/154993177-5949b772-da99-469f-9fff-ffcec4f6e5a4.png">
<img width="1280" alt="Screen Shot 2022-02-22 at 12 18 52 AM" src="https://user-images.githubusercontent.com/17772957/154993194-f41b3c07-4e64-42a8-89e1-b8a549873f91.png">

These `Tags` can be specified on-creation via `Creator Gallery`. Alternatively these tags can be adjusted post-listing via `My Captures` Tab in User Profile.

<img width="1280" alt="Screen Shot 2022-02-22 at 12 23 38 AM" src="https://user-images.githubusercontent.com/17772957/154993650-b3d5d2b5-cc0d-477d-8ca5-cb3fb95af7d5.png">
<img width="1280" alt="Screen Shot 2022-02-22 at 12 23 43 AM" src="https://user-images.githubusercontent.com/17772957/154993691-0ca535d4-09cd-465c-a52b-4a279120ce2b.png">

**Comment by ethanwu155** [comment]
`Filtering My Captures`

We have added a Dropdown on the upper right of `My Captures` Tab that allows users to search through their creations based on the following types: `ALL`, `NFT`, `Gift Cards`, `Capture App`, `Creator Gallery`

<img width="1280" alt="Screen Shot 2022-02-22 at 12 25 48 AM" src="https://user-images.githubusercontent.com/17772957/154994447-85800755-61c4-48be-b772-deb7ebe6fcf4.png">

The hope is that it will help users go through their creations more efficiently as opposed to scrolling through their entire list.

`Showcase specific categories of Capture NFT in CaptureClub`

We've extended this filtering to the `Custom Marketplaces` as well. Custom Marketplaces show all listed NFTs in the marketplace. We have added a Dropdown on the upper right that allows the creator to filter their NFT products based on tags they have designated themselves.

<img width="1280" alt="Screen Shot 2022-02-22 at 12 30 27 AM" src="https://user-images.githubusercontent.com/17772957/154994758-82b0d23c-dfb5-48b1-9067-cabc523a167e.png">

**NOTE:** The option to filter NFT products based on tags is ONLY available to the owner of the marketplace. Visitors of the marketplace will see just the full array of products. In the above image account owner `hinoki` is in `hinoki's marketplace` and is able to access to dropdown filtering. 

<img width="1280" alt="Screen Shot 2022-02-22 at 12 32 58 AM" src="https://user-images.githubusercontent.com/17772957/154995223-77ffba96-79b9-42a7-9f4a-c0f40f2668f2.png">

In the above image account owner `hinoki` is in `Scotta21s` marketplace. Since they are not the owner of the marketplace they do not have access to dropdown filtering.

**Comment by ethanwu155** [comment]
`Shareable Link`

To allow creators to showcase specific works (or portfolios) we have created a shareable link feature, which can be found in the custom marketplace.

To generate a shareable link, creators will do the following:

1) Log in & Navigate to the Custom Marketplace

2) Filter their products based on the category product they want to share
<img width="1280" alt="Screen Shot 2022-02-22 at 12 38 10 AM" src="https://user-images.githubusercontent.com/17772957/154995994-c0e7dc34-3774-4857-bbe6-4f671af2dad1.png">

3) Click on the link icon to generate a shareable link
<img width="1280" alt="Screen Shot 2022-02-22 at 12 38 21 AM" src="https://user-images.githubusercontent.com/17772957/154996239-54396ff7-33b4-4502-8e18-d93d24a7d192.png">

4) Paste link (Ctrl + V or "right click" => paste) to share
<img width="1280" alt="Screen Shot 2022-02-22 at 12 38 57 AM" src="https://user-images.githubusercontent.com/17772957/154996358-e9d31b06-0eff-449b-9540-3a8a8defd13b.png">
