### ISSUE TITLE
Capture App: Organising media using tags, new thumbnail views [FR]

### ISSUE THREAD

**Issue by ghost** [numbersprotocol/community-support#22]
### Proposal
1. To introduce mechanisms of "_tagging_" or adding "_tags_" to the captured media for better organisational capabilities within the app.
2. To introduce ways to enlarge or minimise the size of the media thumbnails / give options for choosing one out of `large`, `small` or `normal` thumbnail sizes. 

### User Story
A user stores lots of media using the Capture App. Whenever he has to retrieve one of his _captures_ he had captured a long time ago, he would need to keep on scrolling till he reaches the required media and/or he has to open some of the nearby _captures_ individually (if they are similar) to check,  which is time consuming. This can be mitigated by 
- Implementing "_tagging_" of the _captures_.
- Providing multiple thumbnail views of the media. (`large`, `small`, `normal`, etc.)

### Additional Context
This has the potential to encourage users to capture more because the retrieval of captured media would be easier.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248721583072) by [Unito](https://www.unito.io)

**Comment by AKT4UnMe** [comment]
I concur with this idea. It certainly will help with the retrieval of images, which is so necessary.

Still, I would like to see "portfolios" implemented too, for simple searches and when presenting on CaptureClub.cc tiered prices can be offered. For example, one series of images are 1/1 and maybe another series are 5/5, 10/10, etc.

**Comment by KNctrl-alt** [comment]
@AKT4UnMe As I read through your recent comment where you explained your views, I have realised that your suggestion was initially intended for the marketplace but I was addressing it from the app only point of view  (given that building a directory system in the app might take some time). 

I do think the marketplace and the app require some difference in their structures since both cater to different purposes. The app is like the source/origin of the digital media in the ecosystem and is also some sort of storage of personal blockchain-registered photos and short videos: a stage before public listing.  On the other hand, the marketplace is a public list of your assets that you think people would want to buy. 

And this is why I tried to be specific to only one of them.

Personally speaking, having albums is certainly not a bad idea and I would be happier if they come to a position to implement both of the solutions. I really appreciate having this conversation with you though. 

Hope our contributions see the day of fruition.

**Comment by AKT4UnMe** [comment]
I understand, please be patient with me for not separating the issues. As an artist/photographer, my thinking is sporadic and intertwined, I’ll do better as I acclimate.

The market place and the app do cater to different purposes. Not being a programmer, I assumed that they’d both be fixed by the folders/portfolios but I understand now that is not the case.

I agree with @KNctrl-alt about the tags. It would be nice to be able to search through my images easier than scrolling all the images.

And the app still needs some photo editing options like Cropping, exposure and temperature control, basic stuff at minimum.

The market place has a lot more progress to be made then the app. Where would I list suggestions for that? 

Thank you

**Comment by KNctrl-alt** [comment]
Hey @AKT4UnMe, I would apologise if my comments came across as a disagreement to your suggestions or as if they are suited only to the marketplace or as if marketplace suggestions cannot be posted here. That's not what I meant. It's also not necessarily the case that the directory system would be too difficult of a task for the team to pursue. It is completely upto the team to choose a solution and go for it, since I am just a passionate community member like you and we are here to provide suggestions as we think are suitable.  

What I wanted was that I start that conversation since we had a similar goal in our mind (to organise media files) so that we could talk more about if one is more feasible than the other for now. It could also be the case that both are seen as good options by the team. As I said, I would be happy if both are adopted. 

However, I do think it would be better if you could take your time and be specific to any part of this ecosystem (or may be even group together parts for your suggestions) and mention it in your issue _Title_ or the _Body_ whenever you post your suggestions. That helps the team and others get exactly the point you want to be delivering. 

@tammyyang, @ethanwu155 and their team have been so lenient and pushing for a community-friendly session in this Phase so no one has to be a programmer to be able to post issues. So you are very welcome to post your suggestions here. We can then discuss about solutions within ourselves and the team and let the team do their part. I think the team would be happier to listen to photographers like you and the issues you have with the products.

By the way, I have been more of a UI/UX enthusiast looking for improvements in the Capture App (hence my submissions about the app) and yet to give a good look at the Capture Club (I have some in my mind, need to narrow it down before I post). So I am really looking forward for your submissions.

**Comment by AKT4UnMe** [comment]
For sure! No stress.

I am new to discussing tech like this in this fashion. I use a lot of tech but never offered suggestions for improvements and I don't talk with a lot programmers or UI/UX folks,so, you know, gotta acclimate to the vernacular.

Yes, I am excited about the Numbers Protocol projects too. I look forward to discussing it and seeing how it develops.

**Comment by tammyyang** [comment]
Portfolio feature is scheduled in the next dev sprint.

**Comment by ethanwu155** [comment]
Tagging Feature is available now in Capture Cam. Despite no longer being actively maintained and discontinued, CaptureClub also had a portfolio type feature as well. This issue is now closed.
