### ISSUE TITLE
Binance listing 

### ISSUE THREAD

**Issue by ParamedicArt** [numbersprotocol/community-support#287]
ParamedicArt:
I think the numbers team can give 5,000,000 num tokens to the binance exchange in exchange for a binance listing. we already give a lot of volume by giving only 1% of 500,000,000 units to be burned in total. we also get great advertising and marketing opportunities.

only the amount to be burned in one quarter can be given to the binance exchange in exchange for listing without being burned

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204672017782504) by [Unito](https://www.unito.io)

**Comment by scott-dt** [comment]
Hi ParamedicArt,

Thank you for your input. We are continually working on getting NUM listed on top exchanges. Unfortunately, due to NDAs and the varying requirements of each exchange for token listing, we are unable to share many details about this process. Rest assured, we acknowledge your feedback and will strive to make the best decision on this matter.

Thank you!
