### ISSUE TITLE
[Community Review] Experimenting with quadratic Mainnet staking

### ISSUE THREAD

**Issue by tammyyang** [numbersprotocol/community-support#313]
## Overview
 
Since we launched Numbers Mainnet last December, we continuously launch programs to incentivize NUM holders to migrate from BSC Chain or Ethereum to the Numbers Mainnet. On the 19th of June, 2023, we announced the launch of a brand-new Mainnet staking pool. This provides new opportunities and platforms for NUM holders to engage and participate in the Numbers Mainnet ecosystem.

Since then, we've observed remarkable enthusiasm from our community. Over 4.6 million Mainnet NUM tokens have been staked in the pool, illustrating the popularity and wide acceptance of this staking pool amongst our users. It's clear that our community has recognized the potential benefits of participating in our Mainnet ecosystem, and we're grateful for their trust and participation.

Nevertheless, we are not oblivious to the evolving dynamics within the pool. It has come to our attention that a single wallet, with a substantial 4 million staked NUM, has shared a significant portion of the rewards. While we understand that this is a result of the stakeholder's active participation and commitment, it has, however, led to an unintended consequence: it has tilted the reward balance in favour of large stakeholders. This has resulted in the Annual Percentage Yield (APY) of the Mainnet staking pool being less than the APY available on other networks, which may not be as appealing to new and smaller stakers. Currently, our Mainnet staking pool pays out an APY of 7% given the current staked amount, which, in comparison to other platforms, may seem modest. 

In response to this, our team is currently assessing potential strategies and alterations that could make the staking pool more balanced and attractive to a broader range of stakers. We want to foster an environment that benefits all, allowing everyone to enjoy the fruits of the participants in Numbers Mainnet. To address this problem, we propose to open up a new staking pool with quadratic rules attached to it, equally splitting the rewards into 2 staking pools running at the same time, one **Traditional Pool** which follows the linear reward mechanism as how most pools work now, another one **Quaractic Pool** with rules described below:

_Any amount of NUM the user stake in the pool, with go through a square root function before being added to the pool._

Example 1 : Bob wants to stake 4 NUM tokens to the Quadratic Pool. The square root of 4 is 2. 4 NUM from Bob will be locked, and Bob will participate and receive rewards from the pool as if he's staking 2 NUM.

Example 2 : Charlie wants to stake 10,000 NUM tokens to the Quadratic Pool. Square root of 10,000 is 100. 10,000 NUM from Charlie will be locked, and Charlie will participate and receive the reward from the pool as if he's staking 100 NUM.

This will allow users to choose a staking pool most suitable to their amount of tokens and rewards. Participation in the **Quadratic Pool** is not mandatory, users are still allowed to choose whether they want to stake only in the Traditional (Linear) Pool, Quadratic pool, or both. It is recommended to participate in the pools best in your best interests.

Here's a simulation to how it will benefit the user if they participate in both pool:

![image (6)](https://github.com/numbersprotocol/community-support/assets/5687908/363ac389-c567-455e-a927-df818bcc425e)

By utilizing both pools, users get more rewards than they would've gotten if they stake only in one pool even with the same amount. They're also free to calculate their own ratio of staked tokens in order to further maximize the staking reward.

This will help both big and small holders to gain fair rewards for the amount of tokens they stake. Big holders can choose to put the majority of their tokens in the Traditional (Linear) pool with low APY, and a small portion of their tokens in the Quadratic pool with high APY. At the same time, small holders can leverage the high APY with low drawback directly by staking to the Quadratic pool.

## Schedule

* Community review: 30th June to  28th Jul
~~* Experimental Quadratic Pool: 31st Jul to 1st Sep with a total of 20K rewards~~
~~* Collect feedback during the experiment and host a DAO vote to determine if we want to keep the Quadratic Pool as the default option on Mainnet or not in Q3 2023.~~
* The Quadratic Pool will be launched alongside the new Mainnet Staking at 25 September

**Comment by Bikso1** [comment]
This process requires careful planning, testing, and community involvement to ensure the mechanism's robustness and resilience against potential attacks. With this, I'm sure the implementation  of this staking mechanism will ensure effectiveness and ensure the long-term success of numbers blockchain network.

**Comment by Varez93** [comment]
I love the concept of having new products and new ways of making passive income. I also love the work being put in by the Numbers team and the support from the community also but I don't really understand why I should be happy with having my 10,000 staked $NUM treated like 100 $NUM. 
This may help the general community but for a capitalist person like me, it doesn't really go well.

As always, this is my opinion...and not a general reflection of the minds of the public

**Comment by Visijo** [comment]
With the team introducing the quadratic method of staking, It will eventually encourage broad participation and reduce the influence of wealthy stakeholders. So going by this Participants voting power will allocate more resources to a specific option progressively more expensive. Since Technical expertise and a deep understanding of blockchain technology are required for successful implementation, then the team are good to go because we the users have that in check already.

**Comment by fredlex** [comment]
It's a good things the team is trying to experiment on new features to ensure the smooth running of the community. However the implementation of the quadratic mainnet staking seem a good idea to ensure stakers are rewarded fairly, gladly it's only an experimental phase to help the team make a better decision that best suites everyone.

**Comment by Aniel756** [comment]
It is exciting to know that the Numbers team is working hard and developing new methods to ensure that both the big and small holders are treated fairly in the pools.

Inasmuch as the APY of the Quadratic pool is far greater and tempting than that of the Traditional pool, the drawback is higher for the big holders than the small holders, favouring the latter more.

The small holders can leverage the high APY and low drawback in the Quadratic pool, while the big holders can leverage the greater benefits associated with the combined pools.

Though this may be experimental, I'm hoping the team will continue to review the reward structure based on the responses from the stakers.

**Comment by Tommy-I-T** [comment]
It is a welcome experiment since there is room for stakers to utilize both Linear and Quadratic pools if they desire so. Although applying the square root function to the amount of NUM tokens staked to make rewards has succeeded in creating a balance, I feel users will tend to stake in the traditional pool more than the quadratic pool.

Over all, I think the Numbers Protocol team is doing a great job.

**Comment by Ohgey** [comment]
The Quadratic pool strategy is a great initiative from the team. This increases the APY rate and as this is a huge factor stakers look out for, it might incentivize more participants to get involved in staking, a win for the team. 
This also benefits smaller stakers whilst giving big stakers the advantage of gaining from the combined pool. 
In my opinion, this is a win win situation.

**Comment by DexstarJay** [comment]
This is an awesome innovation by the #Numbers team. This makes it safer an easier for stakers. Well done!

**Comment by MdRehan05** [comment]
First of all congrats to the team in achieving the community's trust, it's a big achievement that the staking amount reached a 4.6 million $NUM. However with the concentration of rewards in a few hands, the quadratic Mainnet staking looks attractive to small investors like me and i appreciate the team always looking out for the community and not favouring a few participants. Excited to see how this rolls out.

**Comment by BTComrade** [comment]
Its great to see the fairness of having multiple options in terms of staking. the Quadratic staking proposal would be encouraging smaller stakeholders to participate and receive meaningful rewards, also help promote a more decentralized network. bringing balance to large and small investors

**Comment by samxonite** [comment]
Quadratic staking pools seems to distribute rewards more equitably among participants. and might foster stronger community engagement by incentivizing smaller stakeholders to actively participate in the network. getting a diverse range of participants actively involved

**Comment by avie018** [comment]
The quadratic Mainnet staking pool is an exciting change that takes care of the problem of big stakeholders getting unfair rewards. It gives smaller stakes players like me a more appealing choice and gives me more freedom to choose the pool that fits my personal preferences. By using a square root function for staked tokens, the quadratic pool makes sure that larger stake amounts have a proportionally smaller effect on prizes. This makes sure that everyone has an equal chance of winning. This project aims to make the Numbers Mainnet ecosystem more fair so that everyone can enjoy its rewards.

**Comment by mdrizwan-9** [comment]
This new quadratic pool is an amazing proposal. The gap between small and big stakeholder's rewards is lessened. As the staking rewards are decided by the root square function like 4-->2 or        16--->4 big stakeholders are at an disadvantage and will probably favour the linear reward pool. Still a great opportunity for the project to welcome new small stakers and increase community reach.

**Comment by Bikso1** [comment]
The team considering ways to improve the staking pool's balance and appeal to a wider range of stakeholder types in a good development.

The quadratic rules will divide rewards simultaneously equally between two staking pools but experimenting with new staking mechanisms on a blockchain network requires careful planning, testing, and community involvement. It's crucial to consider the potential risks, ensure security and the rest.
With this I'm sure the team will check for the possible loopholes and work on it.

**Comment by emmerson121** [comment]
Introducing linear and quadratic pool allows every user to be carried along. I fully accept the introduction of quadratic pool, for those who want to receive rewards according to what they staked, the freedom is there to switch to linear pool alone but for those who put the interest of the community at heart, they'll go for quadratic pool since at the end, they are not loosing their entire money but just getting part of it as reward.

**Comment by Markie07** [comment]
I like this experiment for the passive income. New staking methods, like the proposed quadratic pool, are needed to address issues with traditional staking. The drawbacks of the old staking method include reward concentration and limited inclusivity. 

The quadratic pool aims to distribute rewards more fairly, encourage participation, and overcome the limitations of linear staking. Experimenting with new methods allows for optimization and a more robust ecosystem. Evaluating outcomes and feedback is crucial for ensuring the effectiveness of the new staking method.

**Comment by Mayasharmark** [comment]
I like the new staking pool with quadratic rules. It will make the rewards more fair and balanced, the current rewards are not very fair, as one wallet with 4 million staked NUM gets most of them as well the current APY of 7% is also not very good. 
this quadratic pool will make it more attractive for smaller stakers like me. Users can also choose between the traditional linear pool, and the quadratic pool, or both. 
I think this will help the network grow and become more diverse and inclusive. I’m going to try the quadratic pool and see how it goes. I think this is a good idea by the Numbers team.

**Comment by PhaeTee** [comment]
The adoption of quadratic pool is fair as its beneficial to all holders. It will encourage maximum participation from community members. Segregation of the skaing pool into Traditional and Quadratic pool also solves the problem of discouragement from Big holders.
It's a win-win situation for all and I think it's amazing.

**Comment by Evagols** [comment]
This is amazing as it will help both big and small holders to gain fair rewards for the amount of tokens they stake. When both pools are utilized, users get more rewards than they would've gotten if they stake only in one pool even with the same amount.

**Comment by Desure01** [comment]
Honestly I love the new staking pool with quadratic rules. 

It seems the rewards looks balanced, the current rewards are not actually fair, 

Like as we see single wallet with 4 million staked, we the quadratic pool rules looks very attractive and it will definitely draw more attention… even to small holders.

**Comment by Probiduc** [comment]
The quadratic Mainnet staking pool is truly a great solution that addresses the issue of unfair rewards for big stakeholders. It empowers smaller players like me with a compelling alternative, granting greater freedom to choose a pool that aligns with personal preferences. By leveraging a square root function, the quadratic pool ensures larger stakes have a proportionally smaller impact on prizes, guaranteeing an equal chance of winning for all. This project strives to foster fairness within the Numbers Mainnet ecosystem, ensuring everyone can savor its rewards.

**Comment by Tahira19** [comment]
It's great that the team is experimenting with new features to ensure the community runs smoothly.

Quadratic Staking will be a key change to Numbers ecosystem. This will be a new ideological milestone for Numbers,  bringing together two  often polarizing concepts to create a more fulfilling and robust  structure.

**Comment by hamza551** [comment]
It's great that the team is experimenting with new features to ensure the community runs smoothly.

Quadratic Staking will be a key change to Numbers ecosystem. This will be a new ideological milestone for Numbers, bringing together two often polarizing concepts to create a more fulfilling and robust structure.

**Comment by valirvan** [comment]
This is awesome move for me, the Numbers team is making the staking pool better for every holders. This quadratic pool will let more people to join and get rewarded, and not just the big stakers. This will also make the pool pay more and be more attractive than other platforms. I like how the Numbers team is honest and creative and I can’t wait to stake my NUM in the quadratic pool.

**Comment by daredevil8871** [comment]
The introduction of the Quadratic Pool alongside the Traditional Pool in Numbers Mainnet offers a fair and flexible staking experience for both large and small token holders. By allowing users to choose their preferred pool or participate in both, Numbers ensures inclusivity and maximizes rewards based on individual staking strategies. These changes demonstrate a proactive approach by Numbers to create a balanced and attractive ecosystem for all stakeholders.

**Comment by nzubezion** [comment]
While the proposed quadratic staking pool is a step towards a fairer distribution of rewards, I personally feel that a more comprehensive solution could involve implementing a dynamic reward system based on a combination of factors like staked amount, staking duration, and overall network participation. This would incentivize long-term commitment, encourage broader participation, and address the issue of large stakeholders disproportionately benefiting from rewards.

**Comment by eserboo** [comment]
Firstly I'm glad that the Team is looking forward to the full community mind and allowing it to be a smooth move.

Quadratic Staking is going to be an essential service to the Numbers ecosystem, in another way It would also make the pool pay more and be more attractive.

With this plan this can attract more than you can imagine.

**Comment by eserboo** [comment]
> Firstly I'm glad that the Team is looking forward to the full community mind and allowing it to be a smooth move.
> 
> Quadratic Staking is going to be an essential service to the Numbers ecosystem, in another way It would also make the pool pay more and be more attractive.
> 
> With this plan this can attract more than you can imagine.

**Comment by fredlex** [comment]
In as much as the cited advantages seem just to everyone. It's also considered to be unfair to some other people and this may be as a disadvantage. 

Any one will feel cheated if they actually staked a higher amount of $NUM And end up sharing same profit ratio as someone who invested very little amount of $NUM. 
Since it's only an experiment, then it could turnout positive or negative and will most definitely require more technical and financial resources to achieve that..  I believe the decision makers will make the right choice for smooth running of the community.. 

Generally practicing the quadratics staking  pool of the numbers mainnet seem a fair enough idea to suit majority of the community

**Comment by CaptainJackSparrow09** [comment]
I'm totally in favour of introducing  the quadratic method of staking, benefiting to all participants. 

Oftentimes the large pool of rewards is only fetched by hyperscalers & super rich, diluting the motivation of small holders to navigate the product further.

Though, it still seems to be an experiment, but I appreciate the way the $NUM team is coming an extra mile for small holders. 

Hoping to see how this reward structure will roll out!

**Comment by eserboo** [comment]
H

**Comment by Jessyweb3** [comment]
This is so awesome for both big and small holders to gain fair rewards for the amount of tokens they stake. This will also make the pool pay more and be more attractive than other platforms.

The NUMBERS team are the best.

**Comment by Possible001** [comment]
It is interesting to know that the protocol considers the general community including small size stakers to also have a part in earning passive income with good estimated APY. Introducing the quadratic staking pool is a welcoming development and a show of good spirit and consideration of community members by the Team

**Comment by Kristeeyo** [comment]
I must commend that this is a really incredible staking idea by the team

Firstly, shout out to the Numbers team for always putting the interest if its community members first

With the implementation of the Quadratic staking pool, individuals are given options to choose which best suits them
Staking will seem a lot more appealing to those everyone and every individual gets to earn fair and square

Really impressive initiative by the team

**Comment by Karen5-hub** [comment]
The team's initiative with the Quadratic pool strategy is excellent. This raises the APY rate, and given that this is a key consideration for stakers, it might encourage more people to participate in staking, which would be advantageous for the team. Congratulations to the team for earning the community's trust. It's a significant accomplishment that the stake amount reached 4.6 million $NUM. limited investors like me, however, find the quadratic Mainnet staking interesting because the profits are concentrated in a limited number of hands. I also admire the team's dedication to the community and lack of favoritism of any particular members. 
While giving major stakeholder the advantage of profiting from this, smaller stakeholder also benefits.

**Comment by cryptomate7863** [comment]
Subject: Feedback on Quadratic Mainnet Staking Proposal

Dear Team,

I appreciate the effort put into proposing the new method of Quadratic Staking for the Numbers Mainnet. After carefully reviewing the document, I would like to provide my feedback on the staking methods and discuss the reasons behind the need for a new approach, as well as the drawbacks of the old staking method.

The introduction of the Quadratic Staking pool seems like a promising solution to address the current challenges faced by the Numbers Mainnet ecosystem. The existing staking pool, while successful in attracting a significant amount of staked NUM tokens, has inadvertently favored large stakeholders, leading to an imbalance in rewards distribution. This has resulted in a relatively lower Annual Percentage Yield (APY) compared to other networks, making it less appealing to potential new and smaller stakers.

The proposed Quadratic Staking pool aims to rectify this issue by implementing a square root function for the staked NUM tokens. This means that the number of tokens a user stakes will be transformed through the square root function before being added to the pool. By doing so, the rewards will be equally distributed among stakers, regardless of the amount staked. This approach offers a more balanced reward mechanism, allowing smaller stakeholders to have a fair chance of receiving attractive rewards and increasing the overall APY.

One advantage of the Quadratic Staking method is that it provides greater flexibility and inclusivity. Users will have the option to choose between the Traditional (Linear) Pool, Quadratic Pool, or participate in both. This allows stakeholders to decide which pool aligns better with their token holdings and investment goals. By offering this choice, you cater to a wider range of participants, encouraging broader engagement and ensuring that everyone can benefit from the Numbers Mainnet ecosystem.

Regarding the drawbacks of the old staking method, the document rightly points out the imbalance in rewards due to the concentration of tokens held by a single large stakeholder. While this stakeholder's active participation and commitment are commendable, it unintentionally resulted in a less attractive APY for the entire staking pool. This could deter potential new stakers and hinder the growth of the Numbers Mainnet ecosystem. Therefore, it is crucial to address this issue promptly and implement measures that promote fairness and inclusivity.

In conclusion, the proposal for Quadratic Mainnet Staking demonstrates a thoughtful response to the challenges faced by the existing staking pool. The introduction of a new pool with quadratic rules offers a more balanced reward distribution, benefiting both smaller and larger stakeholders alike. By providing the option to participate in either pool or both, you empower users to make informed decisions based on their individual interests and token holdings.

I support the initiative to implement Quadratic Staking and believe it will enhance the attractiveness and sustainability of the Numbers Mainnet ecosystem. I look forward to seeing the positive impact of this new staking method and its contribution to a more inclusive and rewarding experience for all participants.

Best regards,
CryptoMate7863
Mohammed Saqib

**Comment by DeFiDebbie** [comment]
First of all, I would like to express my appreciation for the team's effort in always prioritizing their community and ensuring that they are offered equal opportunities. This includes addressing the imbalance within the mainnet staking pool that deprives small stakeholders of significant rewards while favouring larger holders.

However, based on my understanding, during this experiment, the whales will gravitate more towards the option that benefits them the most, which in this case is the traditional staking option.

But, as long as there are multiple options to choose from, this truly makes it a fair approach. So, I hope that after the experimental phase, the staking option can be implemented.

**Comment by DeFiDebbie** [comment]
First of all, I would like to express my appreciation for the team's effort in always prioritizing their community and ensuring that they are offered equal opportunities. This includes addressing the imbalance within the mainnet staking pool that deprives small stakeholders of significant rewards while favouring larger holders.

However, based on my understanding, during this experiment, the whales will gravitate more towards the option that benefits them the most, which in this case is the linear staking option.

But, as long as there are multiple options to choose from, this truly makes it a fair approach. So, I hope that after the experimental phase, the staking option can be implemented.

**Comment by qqorq** [comment]
> 

As long as this builds up to a fairer distribution of $NUM or aligning of incentives, I think its fair to see how it plays out after this

**Comment by ElieTrades** [comment]
This is an impressive initiative. Balancing the disparity in NUM staking rewards between large and small investors is a huge step towards encouraging broader participation by community members. This quadratic pool approach allows for flexibility, enabling users to choose the pool that best aligns with their token holdings and desired rewards. If the experiment is successful, it will go a long way.

**Comment by RisingStar05** [comment]
Actually, the most important thing here is the option to participate in both the traditional (linear) pool and the quadratic pool which provides an opportunity for holders to maximise their rewards by strategically distributing their staked tokens. This gives larger holders the choice to benefit from the stability of the traditional pool while also taking advantage of the higher APY in the quadratic pool. Simultaneously, smaller holders can benefit directly from the high APY offered by the quadratic pool. If one doesn't favour a stakeholder, he won't fall short.

**Comment by rahulkr2503** [comment]
First of all i would like to give my heartiest congratulation to thw whole Numbers Protocol team , that they always thinking of the retail investors in this project. I feel implementation of the quadratic mainnet staking is a good option to ensure staking rewards between large and small investors are rewarded fairly. I support the initiative to implement Quadratic Staking and believe it will bring positive impact for this project in the long run.

**Comment by TylerDylan** [comment]
The Numbers Mainnet team recently launched a new staking pool to provide more opportunities for NUM holders. With over 4.6 million Mainnet NUM tokens already staked, the pool has gained popularity among users. However, the rewards distribution has favored large stakeholders, resulting in a lower Annual Percentage Yield (APY) compared to other networks. To address this, the team is proposing the creation of a new Quadratic Pool with balanced rewards. By applying a square root function to the staked amount, the pool aims to offer fair rewards to both large and small holders. Users can choose to participate in either the Traditional (Linear) Pool or the Quadratic Pool, or both. The team plans to gather community feedback during an experimental phase and conduct a DAO vote to decide whether to make the Quadratic Pool the default option on the Mainnet. The proposed changes aim to create a more inclusive and rewarding ecosystem for all NUM holders.

**Comment by TylerDylan** [comment]
The Numbers Mainnet team has introduced a staking pool for NUM holders, which has gained popularity with over 4.6 million Mainnet NUM tokens already staked. However, the current rewards distribution has favored larger stakeholders, resulting in a lower Annual Percentage Yield (APY) compared to other networks. To address this issue, the team is proposing the creation of a new Quadratic Pool that offers balanced rewards. This pool applies a square root function to the staked amount, aiming to provide fair rewards to both large and small holders. Users have the option to participate in either the Traditional (Linear) Pool or the Quadratic Pool, or both. The team plans to collect community feedback during an experimental phase and conduct a DAO vote to determine whether the Quadratic Pool should become the default option on the Mainnet. These proposed changes aim to establish a more inclusive and rewarding ecosystem for all NUM holders.

**Comment by Giftino** [comment]
Thank you for addressing the issue and proposing a solution. Opening a new staking pool with quadratic rules is an innovative approach that aims to create a more balanced and attractive environment for a wider range of NUM holders. This demonstrates Numbers' commitment to inclusivity and ensuring that all NUM holders can benefit from the rewards.

**Comment by Giftino** [comment]
I appreciate the team's efforts in evaluating new staking methods to enhance the balance and appeal of the staking pool. By introducing quadratic rules and splitting rewards between Traditional and Quadratic Pools, this aim to create a fairer and more inclusive environment for participants. The square root function applied to staked NUM adds a unique twist, potentially attracting a broader range of stakers. This innovative approach demonstrates a commitment to improving the staking experience and fostering wider participation in Numbers Mainnet.

**Comment by Steffdarz** [comment]
Glad seeing everyone were looking forward to this new Staking Pool. Thank you for everyone's feedback, we will be concluding this Community Review and proceed with launching the new Staking Pool
