### ISSUE TITLE
Kucoin NUM - Mainnet 

### ISSUE THREAD

**Issue by Nyce1987** [numbersprotocol/community-support#314]
Hello Team, i hope everything is fine.

I wanted to know, if there are any future plans to support Numbers Mainnet on Kucoin. I have been investing in NUM since November 2021. I made a mistake. After I claimed my coins from the first single MAINNET staking and sent them to Kucoin to continue staking, I sent them to the wrong chain (BEP20). I contacted the support team at Kucoin. They reply me that they can't do anything at the moment as long as the NUM don't support Mainnet. I can't get my coins at the moment. 

I look forward to your reply 

with kind regards

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1204935993870573) by [Unito](https://www.unito.io)

**Comment by tammyyang** [comment]
Yes, it is in the plan and under negotiation, but the actual schedule may depend on KuCoin.
Our team member had done something very similar before, but we had successfully get the fund back from KuCoin.
I strongly suggest that you contact KuCoin support again and ask them to send your fund back since it's your assets.
As a CEX that providing services, I believe this is something they can do.

**Comment by Nyce1987** [comment]
Hello Tammy,  
is there any progress or news about the negotiation on kucoin for numbers mainnet?

With kind regards

**Comment by Nyce1987** [comment]
@tammyyang I would be happy if you would say something about it.
