### ISSUE TITLE
Feature request or issue report for our Monthly Dev Call (2nd)

### ISSUE THREAD

**Issue by kennyhungQA** [numbersprotocol/community-support#320]
Hey there, our second Dev Call is coming soon!

Got a question about our products? Itching to know more about that feature you love? Or perhaps you've got an awesome idea that you're just dying to share? We're all ears! Tell us what do you expect to see from Numbers Protocol.

No query is too big or too small. Every thought, every question you have, plays a vital part in shaping the future of our monthly dev call – and we're beyond excited to hear them all!

Remember, this community thrives on your voice and we're here to provide the answers you need. So, why wait? Leave your questions in the comment NOW and stand a chance to receive a unique NFT! Let's continue building this incredible community, one question at a time.

Together, we can make a difference.

Save the date! Join us for the Monthly Dev Call on July 27th at 12:00 UTC in Numbers Discord channel "Numbers Stage”. See you again!

📍Venue: https://link.numbersprotocol.io/NumbersStage

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1205091884488579) by [Unito](https://www.unito.io)

**Comment by Lasheron** [comment]
Feature Request: 
Features such as login password, fingerprint unlock, pattern passcode and two factor authentication should be added into the app for security of the wallets of users as well as their captures.

**Comment by Profkingkeys** [comment]
Feature Request:
They should be p2p so we can use fiat to purchase $NUM from other Capture users and the should be more filters and camera effect.

**Comment by emmerson121** [comment]
Features like KYC, 2FA should be introduced to further strengthen the security of the Capture and more effects should be added in the camera

**Comment by DexstarJay** [comment]
I think there should be a way someone can easily convert his/her $NUM token to fiat in the Capture App without needing any third party app or platform to do that. If we can have such feature in the Capture app, it will be unbeatable.

**Comment by Ohgey** [comment]
I totally subscribe to the more filters and effects feature, it adds utility to the app. Developers should work on device accessibility as the app is not available on playstore with most devices limiting wide use. Features like motion pictures, camera rotation should be added as well. Sessions time out also helps to strengthen security should incase you log into another device and forget to logout from the device.

**Comment by Visijo** [comment]
Talking of compatibility, I think something should be done by the developers in other for the app to be compatible with many devices and not a selected few.
Improved security also to avoid stealing of data.

**Comment by Bikso1** [comment]
Kudos to the team for their hard work and always listening to the community. To add to this feature request, I suggest the capture app user interface should be a bit modified with enhanced filters, security measures should be checked as well, issues of third party coming in just to swap the $NUM token should be looked into, thanks.

**Comment by Varez93** [comment]
Fair to say that I am impressed with the job done by the team behind the scenes, especially relating to my capture app having issues. Now I can use my capture app to take iconic images and register on the blockchain.

I might also want to look at the possibility of having fiat on-ramps on the capture app so that I can buy $NUM directly with fiat on the app. 

I'd also want the capture app to have more edit features for images. Right now it's just black and white/colour. 

Also the Numbers Search Engine should have just own mobile app. 

For now, every other thing seems okay to me on the capture app.

**Comment by daredevil8871** [comment]
First of all hats off to the developers coz from the last dev call I have not faced any issue in Capture App till now. 
Feature request: Pls add some live filters which we can use when taking captures like Portrait mode, HDR, and AI scene recognition & Pls add the option of pattern, passcode & biometrics in the app & especially in the wallet section. One more request it's good if the wallet also reflects the value of Num that we hold in usdt.

**Comment by DeFiDebbie** [comment]
Feature Request

R1
Could you integrate pass security into the Capture App such as face unlock? This is for people who like their privacy and security. The reason is, our wallet and integrity key are open for anyone to access. It could lead to a security breach. 

R2
In the App, there is no section for works that have been minted or sold. It makes losing track of your creations and transactions easier. Better organisation is highly recommended.

**Comment by RisingStar05** [comment]
First of all, I want to appreciate the team for the hard work they put into the success of this project. 

However, I do have a little suggestion for the Capture App. I have used the app's shorts options once and realised that it doesn't record sound, just motion. 

I believe this could be easily worked on as it would improve the use of Capture shorts for future use.

**Comment by Tahira19** [comment]
Features request :

1. Offer the option to set a passcode or use biometric authentication  (e.g., fingerprint or face recognition) to protect the data.

2. Provide tools to enhance the scanned image, such as adjusting  brightness, contrast, and color balance, to improve readability and  overall quality.

**Comment by Tommy-I-T** [comment]
My Capture App experience have been good but I have two request:
1. 2FA addition
2. Photo editing features including frames.

**Comment by Aniel756** [comment]
So far, I don't have any issues, aside the Captures taking little more time to upload.

I'll request :
1. A 2FA features
2. Web3 logins process instead of the current Web2 ( email and password)

**Comment by Probiduc** [comment]
I would love to see Numbers Protocol expand its compatibility across different platforms (e.g., mobile, web, desktop) to enhance accessibility and user experience.

**Comment by fredlex** [comment]
With a good job done so far, I would like to suggest that 

1. the capture dashboard features be incorporated into the app, making it completely handy and I think the user interface of the capture app be improved.

2. AI generation can also be established within the capture app as this will help identify Ai generated media using a special badge.

3. The security within the app should be improved. A major upgrade on the login options should be done granting access to more authentic users. (Kyc, fingerprint, google authenticator etc)

4. If creating a direct exchange of NUM for fiat may prove expensive, swap of capture credit for NUM can be implemented since 
1 capture credit = 1 NUM token

**Comment by 12divine** [comment]
Well i haven't experienced any glitches recently, I would say everything works fine

**Comment by Karen5-hub** [comment]
I think that the software is more useful with the addition of more filters and effects. Since the app is not on the Play Store and most smartphones have limitations that prevent widespread use, developers should focus on device accessibility.

For the security of users' wallets and their captures, the app should include features like login password, fingerprint unlock, pattern passcode, and two factor authentication.

**Comment by nzubezion** [comment]
Capture App is incredibly awesome right now, but here are a few things I'll love to see

1. A security system: Right now, when you are logged into the app, anyone with access to your device can easily log into your capture app, take your integrity key and have fun with it. My suggestion is that the camera section be open to all, but the wallets section be secured by a password system (Be it pin, pattern, face recognition or biometrics)

2. Exploring Capture App is fun, but once you have a budget, it means opening each and every capture individually to check the cost. That can be draining and discouraging to impatient people, I'll suggest fixing it up in a way that the prices can be seen without clicking on each capture.

That's all from me for now, every other feature is incredible

**Comment by Markie07** [comment]
Features request In the capture app, enhance security with login passwords and two-factor authentication for user wallets. Implement fingerprint and pattern unlock options for convenient yet secure access to captures. Safeguard sensitive data with encryption, providing real-time alerts for added protection, and ensure transparent privacy policies for user confidence.

**Comment by Mayasharmark** [comment]
First its good to know that there is another monthly dev call. 

FEATURE REQUEST: new update are on products are good but I think adding p2p transaction would be more easy since capture are having wallet. It would be more accessible especially for those who have NUM token on capture wallet.

**Comment by avie018** [comment]
I do not see a name changer in the application. It is difficult for me to adjust the capture app. I previously entered my email address incorrectly. However, I am now having trouble changing it.

**Comment by samxonite** [comment]
Feature request: Real-Time Notifications, Implement real-time push notifications to keep users updated on activities related to their contents

**Comment by BTComrade** [comment]
Feature request: Social Feature, Incorporate social elements, such as sharing media with friends or a broader community, liking, commenting, and following other users. This can create a sense of community within the app.

**Comment by PhaeTee** [comment]
Feature request

I recommend the addition of security features like biometrics verification, password and 2-FA to avoid access without users permission.

**Comment by Possible001** [comment]
Feature Request
I'd suggest for a share button sort of where you can share your captures to social media platforms directly from your capture app 

I'd also recommend a security feature like a password to be enabled in order to allow only authorized users access into the app

**Comment by valirvan** [comment]
feature request: 
additional security for all assets like login biometric , and authentication password aside from email . verification of email before using the entire application. 

More security added much better for users assets.

**Comment by ElieTrades** [comment]
The app has been great so far, but it can be better. I noticed that purchased NFTs are still displayed in the CaptureApp marketplace. This adds to the frustration we, as buyers, have when having to click on every individual photo to check out the prices.

**Comment by Desure01** [comment]
I would recommend Numbers Protocol to extend expand their products across the world like having a real life company where they produce a life use camera to explore and make the camera even brighter than iPhone..

But meanwhile they are still the best for me. I love ❤️ Capture App …

**Comment by DexstarJay** [comment]
Users should be able to run P2P easily in the Capture app without any third party app, we need more filters as well.

**Comment by Kristeeyo** [comment]
Capture App has been doing well but the app lacks tight security and it makes captures and wallets accessible to anyone

That's my major feature request

**Comment by eserboo** [comment]
My friends have been asking for more filters in the Capture App, 
But the app has been great and I became a photographer. Please the team should look into my requests.

**Comment by WEB3Queen01** [comment]
Its awesome to have another dev call . The recent updates on capture app is really good . and I know it will be much better if you can add some features . 

what if we want to exchange our tokens for fiat money? 
Or what if we  want to protect our wallet and integrity key from unauthorized access? 

That’s why I think it will be better to have additional two features such as a built-in converter to fiat and a face unlock option for security. These features would make the Capture App more convenient, secure .

**Comment by Giftino** [comment]
To enhance the security of the Capture App, it is essential to implement additional features such as KYC (Know Your Customer) and 2FA (Two-Factor Authentication). 

These measures will fortify the app's protection and safeguard user data. Moreover, enriching the camera with more effects will elevate the user experience, offering a diverse range of creative options to capture and share memorable moments. By incorporating these improvements, the Capture App can ensure both security and enhanced functionality, fostering a safer and more enjoyable user journey.
Thanks.

**Comment by hamza551** [comment]
Feature request: 

The core feature of the app is to scan documents. It should allow users  to capture images of documents with the smartphone camera and  automatically detect edges, straighten the image, and crop unnecessary  borders.

**Comment by ethanwu155** [comment]
> I think there should be a way someone can easily convert his/her $NUM token to fiat in the Capture App without needing any third party app or platform to do that. If we can have such feature in the Capture app, it will be unbeatable.

We understand that many of users want a way to acquire NUM Token in-app. Unfortunately we are limited by app store regulations. We have been able to work around this with the implementation of NUM Credits system that allows users to utilize services provided by Capture App. We also recently implemented a ETH to NUM Swap feature in Capture Cam that allows users to swap their ETH for NUM.

We understand the community wants more and the team will continue to investigate ways for the community to acquire NUM token in-app. Appreciate your comment and patience.

**Comment by ethanwu155** [comment]
> I totally subscribe to the more filters and effects feature, it adds utility to the app. Developers should work on device accessibility as the app is not available on playstore with most devices limiting wide use. Features like motion pictures, camera rotation should be added as well. Sessions time out also helps to strengthen security should incase you log into another device and forget to logout from the device.

Appreciate the feedback. Additional camera features is something we are aware the community wants. Right now we are working hard on ensuring that the current Capture is stable. We want to reduce the number of critical issues and crashes. For context, we have been spending a period of time fixing issues related to the camera (which was the root of many issues). This camera has just the basic functions. 

So at the present time, we most likely will not be adding any advance camera features as the complexity of integration is quite challenging. In the future, once things are more stable and settled, we can look to add additional camera functions. Of course this can change depending on whether or not certain partnerships come up that makes it easier to implement or requiring us to to make it a higher priority.

Appreciate your feedback and understanding. We will add your request to the product backlog.

**Comment by ethanwu155** [comment]
> My friends have been asking for more filters in the Capture App, But the app has been great and I became a photographer. Please the team should look into my requests.

I'm glad that you are using the app and are enjoying it.

Your request for more filters is noted. Currently we support black and white filter. The reason for this is because we wanted photos created with Capture Cam to displayed "as is" to represent their authenticity. 

Despite that, I think this is something that can be discussed further. We will add this to the product backlog. Thanks for your request!

**Comment by ethanwu155** [comment]
> Feature Request: i wanted to request push notifications whenever the capture has been fully registered on the blockchain. Also is there a possibility to add a video section like the capture discovery but without audio so it doesn't resemble short video apps at the same time. Excited to talk with y'all in the Dev call on Saturday!

Thanks for the feature request. I believe Capture Cam already has some notifications already (when assets are successfully minted & shared). if you want more notifications, this is something we have been discussing. We will take note of your request when we are determining the schedule. 

Currently the Explore tab is just the Marketplace. I think a common misunderstanding (a failure on our part to communicate effectively) is the value proposition of Capture which is a "Web3 Asset Management Tool with On-Chain Provenance and simple UX". Capture is not a social media application. So while I understand the desire to have it function like familiar application such as Instagram, YouTube, TikTok it might be better to think of Capture as a tool rather than social media. 

I hope that clarifies things for you. That's not to say we will never insert any familiar social media features in the future (never say never) but at present time we are focused on working on features that fulfill the value proposition. In the mean time we will definitely add it to the product backlog and go from there. If the community and user base becomes big enough and its something that they are clamouring for, I can see this feature making it into Capture.

**Comment by ethanwu155** [comment]
> Feature Request I'd suggest for a share button sort of where you can share your captures to social media platforms directly from your capture app
> 
> I'd also recommend a security feature like a password to be enabled in order to allow only authorized users access into the app

Thanks for your feedback. I agree, the sharing functionality is currently limited to just sharing asset profile url. I think there is space for something like direct sharing to IG, Pinterest, etc. We will add this to the product backlog and discuss further. Thanks!

**Comment by ethanwu155** [comment]
> Capture App is incredibly awesome right now, but here are a few things I'll love to see
> 
> 1. A security system: Right now, when you are logged into the app, anyone with access to your device can easily log into your capture app, take your integrity key and have fun with it. My suggestion is that the camera section be open to all, but the wallets section be secured by a password system (Be it pin, pattern, face recognition or biometrics)
> 2. Exploring Capture App is fun, but once you have a budget, it means opening each and every capture individually to check the cost. That can be draining and discouraging to impatient people, I'll suggest fixing it up in a way that the prices can be seen without clicking on each capture.
> 
> That's all from me for now, every other feature is incredible

Thanks for the feedback. Addressing #2 we have a feature to display NUM prices in the product page in the works so look out for that. Hopefully that will help streamline the capture exploration :)

**Comment by ethanwu155** [comment]
> The app has been great so far, but it can be better. I noticed that purchased NFTs are still displayed in the CaptureApp marketplace. This adds to the frustration we, as buyers, have when having to click on every individual photo to check out the prices.

Thanks for the feedback. What you point out is maybe a failure on our part to design a strong UX for Capture Explore page. We will add this issue to the product backlog and circle with our UI / UX designer to see what we can do about this

**Comment by ethanwu155** [comment]
> Feature request:
> 
> The core feature of the app is to scan documents. It should allow users to capture images of documents with the smartphone camera and automatically detect edges, straighten the image, and crop unnecessary borders.

Thanks for the request! I think a document scan support is actually quite interesting. We have registered pdf files to our network as apart of the 2022 archive. Support for pdf files or scan documents is something I can see in the future. 

As always we will add this to the product backlog. Currently we are working towards audio, 3D file support. Support for pdf / scan feature could follow. Thanks again for the feedback!

**Comment by ethanwu155** [comment]
> Feature Request
> 
> R1 Could you integrate pass security into the Capture App such as face unlock? This is for people who like their privacy and security. The reason is, our wallet and integrity key are open for anyone to access. It could lead to a security breach.
> 
> R2 In the App, there is no section for works that have been minted or sold. It makes losing track of your creations and transactions easier. Better organisation is highly recommended.

Thanks for your feedback. As mentioned before Captures value proposition includes asset management and Debbie’s comment highlights our failure to deliver on value proposition. 

For this one we will probably create a high priority task card and discuss with our designers on how best to improve the Capture UI to better serve the asset management needs of our users. 

Once we iron out that design we can implement and hopefully deliver an improved experience.

Since this item is a high priority, you can expect to hear some updates on GitHub issues whenever they become available.

**Comment by rahulkr2503** [comment]
Congratulations to the Numbers Team for constantly putting hard efforts for the project.
It's really nice to have a monthly call every month, which really engages the community.
I would like to request some add on features for the Capture App to make competitive with all recent apps - Please try add some funny filters which we can use when taking captures.
Add some sound features in the app also bring something for security purposes like pattern, facecode etc in the app.

**Comment by TylerDylan** [comment]
I notice the capture app compatibility has been fixed, and I think that's really good progress from the team..
I suggest we also have a way of purchasing NUM through the capture app from other users, like p2p, and also that the capture app has more security features to protect our funds

**Comment by ethanwu155** [comment]
> Features like KYC, 2FA should be introduced to further strengthen the security of the Capture and more effects should be added in the camera



> With a good job done so far, I would like to suggest that
> 
> 1. the capture dashboard features be incorporated into the app, making it completely handy and I think the user interface of the capture app be improved.
> 2. AI generation can also be established within the capture app as this will help identify Ai generated media using a special badge.
> 3. The security within the app should be improved. A major upgrade on the login options should be done granting access to more authentic users. (Kyc, fingerprint, google authenticator etc)
> 4. If creating a direct exchange of NUM for fiat may prove expensive, swap of capture credit for NUM can be implemented since
>    1 capture credit = 1 NUM token



> To enhance the security of the Capture App, it is essential to implement additional features such as KYC (Know Your Customer) and 2FA (Two-Factor Authentication).
> 
> These measures will fortify the app's protection and safeguard user data. Moreover, enriching the camera with more effects will elevate the user experience, offering a diverse range of creative options to capture and share memorable moments. By incorporating these improvements, the Capture App can ensure both security and enhanced functionality, fostering a safer and more enjoyable user journey. Thanks.

This comment is in response to KYC. Capture is a web3 asset management tool with on-chain provenance and simple UX. Because there are blockchain elements to this application we have created a wallet with basic features (deposit, send, ETH - NUIM Swap). Since Capture is not to be a fully fledged wallet application we believe KYC is not necessary at this time. 

Thanks for your inquiry. Let us know if you have any additional feedback.

**Comment by ethanwu155** [comment]
> Congratulations to the Numbers Team for constantly putting hard efforts for the project. It's really nice to have a monthly call every month, which really engages the community. I would like to request some add on features for the Capture App to make competitive with all recent apps - Please try add some funny filters which we can use when taking captures. Add some sound features in the app also bring something for security purposes like pattern, facecode etc in the app.

thanks for the kind words. we have many requests for filters. we will add this to the product backlog and discuss further if its in the best interest of capture to support more filters. Thank you!

**Comment by sofiayan0523** [comment]
**July Post Dev Call Summary**
- Date: July 27, 2023 8:00 PM - 8:45 PM (Taipei Time)
- [Recording](https://reccloud.com/tw/u/cbitg6j)
- [Slides](https://docs.google.com/presentation/d/15EMGdW0GbXRBiPMnumO6FkJCy8AC8zDM8dEBQciJEuM/edit#slide=id.g258bd8593ad_0_219)

Numbers Team:
- Ethan Wu - Developer (Host)
- Kenny Huang - QA (PowerPoint Operator)
- Sofia Yan - Marketing (Call Support)

Dev Call Structure
- Introduction : Greetings, Goals for Call, Agenda
- Product Updates
1. EIP 7052 : Interoperable Digital Media Indexing
2. Capture Eye
3. Capture Cam Issue Summary & Fix
4. NUM Development - July Open Staking Pools

Product Roadmap (subject to change): 
Q3 Roadmap : 

- Generative AI Integration 
- EIP Proposal (AI mining preference, digital sourcing)
- Asset Profile Updates
- IPFS Batch Support
- Audio File support
- Capture Cam / Dashboard Improvements
- Updated Pricing Plan

Q4 Roadmap
- NFT Import
- Batch Commit support
- Numbers Handle
- Search Engine Integration in Capture
- Enhance login security
- 3D File support

Product Feedback (x4) : Topics Covered
- Additional Security to Capture Wallet (Biometrics, 2FA, etc.) 
- Additional Camera functions (HDR, Portrait, Filters) 
- Additional methods for acquiring NUM, NUM to Fiat options
- Capture UX issues specifically related to Explorer Page

Open Feedback Session (10+ minutes)
Announcements : Instill Partnership Announcement Preview

Planning:
- Logistics (scheduling rehearsal, posting GitHub, scheduling dev call date / time) for the dev call was handled by Kenny
- Materials (Slide & Script) was handled by Ethan with team support for edits and modification
- Announcements on Social Media and graphic creation was handled by Sofia

GitHub Issues
Issue Thread : Feature request or issue report for our Monthly Dev Call (2nd) #320

Primary Developer Responder : Ethan Wu
Top Issues / Comments (bolded issues addressed in Dev Call) : 
- Additional Security to Capture Wallet (Biometrics, 2FA, etc.) 
- Additional Camera functions (HDR, Portrait, Filters) 
- Additional methods for acquiring NUM, NUM to Fiat options
- Capture UX issues specifically related to Explorer Page
- Add KYC to Capture
- Positive feedback for Capture Cam Issue Fixes
- Add Dashboard features to Capture Cam

Notes
- Discord Platform had issues due to lack of server boosting. This led to a max attendance of 50 resulting in some community members unable to attend. Need to consider a better platform for future meetings to better accommodate high volume of attendees
- Notable Numbers Protocol Attendees: Ethan, Kenny, Sofia, Tammy, Bofu

**Comment by cryptomate7863** [comment]
Can you provide more details about the upcoming features in the Numbers Protocol? Are there any exciting updates or improvements that the community can look forward to?

I'm curious about the NFT functionality in Numbers Protocol. How does it work, and what are the potential use cases for NFTs within the platform?

Are there any plans to enhance the security and privacy features of Numbers Protocol? With the increasing concerns about data breaches and privacy violations, it would be great to know how the team is addressing these issues.

I have a suggestion for improving the user interface of the platform. Where can I submit my idea, and how does the team prioritize community feedback for future updates?

How is Numbers Protocol fostering community engagement and encouraging developers to contribute to the project? Are there any plans for hackathons, bounties, or educational resources for developers?

Can you share some insights into the roadmap for Numbers Protocol? What major milestones or goals does the team plan to achieve in the coming months?

I've heard about other blockchain scaling solutions. How does Numbers Protocol compare to them in terms of performance, efficiency, and cost-effectiveness?

With the growing interest in decentralized finance (DeFi), is Numbers Protocol exploring any integrations with popular DeFi projects or platforms?

As a community member, how can I actively contribute to the growth and success of Numbers Protocol beyond participating in the Dev Calls and discussions on Discord?
