### ISSUE TITLE
Feature request or issue report for our Monthly Dev Call (Sep)

### ISSUE THREAD

**Issue by kennyhungQA** [numbersprotocol/community-support#330]
Hey there, our Dev Call is coming soon!

Got a question about our products? Itching to know more about that feature you love? Or perhaps you've got an awesome idea that you're just dying to share? We're all ears! Tell us what do you expect to see from Numbers Protocol.

No query is too big or too small. Every thought, every question you have, plays a vital part in shaping the future of our monthly dev call – and we're beyond excited to hear them all!

Remember, this community thrives on your voice and we're here to provide the answers you need. So, why wait? Leave your questions in the comment NOW and stand a chance to receive a unique NFT! Let's continue building this incredible community, one question at a time.

This time, our partner "Instill" will also be joining the Dev Call. They will introduce their product, marking our first AI + blockchain collaboration.

Save the date! Join us for the Monthly Dev Call on Sep 14th at 12:00 UTC in Numbers Protocol Youtube channel. See you there!

📍Venue: https://link.numbersprotocol.io/DevCall

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1205433021234863) by [Unito](https://www.unito.io)

**Comment by ethanwu155** [comment]
### **September Dev Call Summary**

**Summary**

This months Dev Call deviated from the usual development and issue addressing agenda and instead focused on the Numbers Protocol and Instill AI partnership in the hopes of introducing AI and Blockchain to a wider audience. Because of this deviation, the September Dev Call took on a webinar format in the hopes of better serving our potential audience which included Numbers Community Members, Developer, Business Partners, AI & Blockchain enthusiasts, Creators and more.

**Dev Call Details**

Date: September 14th, 2023 at 12:00 UTC
Title: AI meets Blockchain : How to create generative AI content with blockchain provenance using low-code tools
Platform: YouTube Live Stream
Live Stream Link: https://link.numbersprotocol.io/DevCall

**Platform Adjustments**

Due to complications with Augusts Dev Call, the Numbers Protocol team has been investigating alternative platforms for delivering our Dev Calls. Our investigation led us to YouTube Live Streaming as the most ideal platform given its lack of limitations regarding how many people can attend and the general flexibility of the YouTube platform (automatic VOD, chat, etc.)

Our first time using YouTube Live Stream has confirm our thoughts regarding the platform and moving forward we will continue to use it to deliver our Dev Calls.

**Topics Covers**

- Generative AI Overview
- Blockchain Solution
- Numbers Protocol
- Instill AI
- Low Code AI + Blockchain Demo Application
- What's Next

Complete Slides: https://docs.google.com/presentation/d/1yp0NnLoTQjvpMyK9g4ECe-80Moi54GtmMEsckMW8o-4/edit

**Statistics**

- Duration: 38:39
- View (at the time of stream): 114
- Peak Concurrent: 42
- Average View Duration: 12:01
- Chat Rate: 8
