### ISSUE TITLE
The amount of locked token in the staking page is not accurate

### ISSUE THREAD

**Issue by Steffdarz** [numbersprotocol/community-support#372]
Currently the amount of locked token in Numbers Official staking page is inaccurate and does not represent the real amount of staked token real time.

For example let's go to the page of recently closed quadratic staking pool : https://app.num.network/staking-mainnet-008

![Bug 1](https://github.com/numbersprotocol/community-support/assets/125893443/fce94c97-ac52-4fec-86f1-73a67b8fb17c)
We can see that the staked amount indicated in this page is '1015570.0000 NUM'

But on checking the actual staked token amount in the mainnet explorer contract address, we see the following

![Bug 2](https://github.com/numbersprotocol/community-support/assets/125893443/1430dba7-95e5-4a13-b91c-1d82eff1227e)
Turns out there's only less than 500,000 staked NUM left in the contract.

The number of staked NUM in the staking page should indicate the correct amount of staked NUM left as shown in the mainnet explorer.

​
┆The issue is also created on [Asana](https://app.asana.com/0/1203248692432071/1207638063344335)

**Comment by scott-dt** [comment]
Dear User,

Thank you for reporting the issue regarding the Numbers Official staking page.

We have noticed that the amount of locked tokens displayed on our staking page is inaccurate and does not represent the real-time amount of staked tokens. Here are the specific issues we have identified:
On the recently closed quadratic staking pool page ([link](https://app.num.network/staking-mainnet-008)), the staked amount indicated is '1015570.0000 NUM'.
However, upon checking the actual staked token amount in the mainnet explorer contract address, it turns out there are less than 500,000 staked NUM left in the contract.
We understand that these display issues can affect your operations and decisions. We have reported these issues to our technical team and will arrange for a fix as soon as possible to ensure that the staking page accurately reflects the actual staked amount in the mainnet contract.
Thank you again for your support and patience. If you have any further questions or need assistance, please do not hesitate to contact our customer service team.

Best regards,

The Numbers Team

**Comment by scott-dt** [comment]
The issue you reported has been resolved in the latest staking pool. Thank you for bringing it to our attention, and please let us know if you need any further assistance.
