### ISSUE TITLE
Additional bounty [Text content demand] Podcast Recap - Phil Chen

### ISSUE THREAD

**Issue by sofiayan0523** [numbersprotocol/community-support#43]
The 【Behind the Project】Ep2 is online!
Looking for #NUMARMY to help with the recap on text!

Qualification:
1. Must have listened to the [podcast](https://youtu.be/HODQqnBsgKg)
2. Must use readable English
3. Must have good article structure, it has to be a digest of the podcast, can not be interview transcript, [example](https://medium.com/numbers-protocol/behind-the-project-opening-episode-angel-investor-steve-chen-aadea2615ce8)

Rewards:
- 50 NUM for the whole article.
- Bounty-based, the reward is from the ambassador reward pool.
- If you finish the additional task, you're automatically qualified to join Tier 2 ambassador program.

How to submit?
- The content should be done as the Github issue comment.
- Share the link of the comment in the global community (Telegram or Twitter) and get at least 3 likes on Github.
- If there are two comments both collect 3 likes, the earlier one wins.

**Comment by KNctrl-alt** [comment]
### Recap of Second Episode 
## Angel Investor : Phil Chen

_In this podcast “ Behind the Project”, we conduct interviews with significant associates, including our investors and partners to share the stories behind the project._


For the second episode, we invited as guest, another significant investor and advisor of Numbers Protocol, Phil Chen, for having discussions on the evolution of internet towards web3.0, NFTs and the significant role that Numbers Protocol is going to play in this field.

From it's very beginning, Numbers Protocol has been working to bring authenticity and trust in digital media by building a decentralised photo network by leveraging the blockchain technology. In a time when propagation of misinformation / manipulated information is on the rise, Numbers' network provides a chance for the digital assets to retain crucial information like ownership, context and history throughout it's lifecycle.

In this episode, we started our conversation by talking about the recent trends in crypto, nfts and web3.0. These trends are witnessing rapid growth in attention from people around the world and it's crucial for us to understand if it can truely bring about revolutionary changes instead of being just a bubble. Talking about it, Phil shared how essential it is for new projects to adhere to the foundational principles of crypto, namely, being borderless, permissionless, censor resistant, open and decentralised. Compromising in any one of these principles would only make the project lose its place as a web3 technology. He said that despite challenges, developing gaming projects, NFT marketplaces and other projects without centralised systems would bring the true revolution, following the true ethos of crypto. 


Making comparisons with websites, he said, people these days want to obtain NFTs just like every company wanted to have their own websites during the early 90s. He also shared his insights on the metaverse, which would be a point in time when people would give more value to digital assets, and also spend most of their time experiencing virtual relationships and environments. These newer avenues are definitely exciting for him but he expressed the importance of not compromising in any of the principles mentioned earlier.


Moving the discussion to Numbers Protocol, he shared what he sees as opportunities for the project and what excites him the most. Referring to what  Numbers is currently trying to achieve with it's NFT search engine, he said that it is answering some of the most important questions about NFTs like who created it, did he/she really create it, etc. Extending this idea, he thinks in the future, people will no longer have to go to Google for searching the truth but they will instead look into onchain data of blockchain networks using search engines built for those purposes. This would make the process of authentication and verification a lot easier and trustworthy in comparison to searching on most web 2.0 search engines which have ad-based models. That is the benefit of web 3.0 technologies because they can be mission driven instead of profits and attention.

He expressed great confidence in the team behind Numbers Protocol and stated how their experience in open source projects, world wide collaborations, bringing communities together and managing them led him to believe in the mission of this project which further led him to investing in it.
He was also appreciative of how the team treated the community members as partners instead of customers, enabling them to have deeper engagements with the people. 

Finally he stated how journalists and media houses would make the most use of Numbers' network. Since currently, there are no ways to authenticate news material shared by them, Numbers' would provide them a way to "build integrity around their journalism".

**Comment by Sirbidex22** [comment]
Cool and interesting

**Comment by sofiayan0523** [comment]
@KNctrl-alt Thank you for your contribution!
The recap article is approved and pushed to Numbers Medium with your name, please check it here: https://link.medium.com/jYN2MeyjZmb

Thank you for your contribution, please [fill out the form](https://airtable.com/shrHsGWu0uN1r2sYj) to claim your reward :)

**Comment by KNctrl-alt** [comment]
@sofiayan0523 Thanks for the response. I have submitted the form. 💯
