### ISSUE TITLE
issues report note

### ISSUE THREAD

**Issue by scott-dt** [numbersprotocol/community-support#44]
Thank you very much for taking the time to test new features. Your help in this area greatly assists us in ensuring that newly developed functions can be improved .
If you encounter any problems and areas that can be improved during use, you are welcome to use github issues to report.
Please use the following template for reporting to expedite our integration and schedule corrections.

================================================================
  1. **Describe the bug**
       

  2. **To Reproduce**

  3. **Expected behavior**

  4. **Screenshots**
      If applicable, add screenshots to help explain your problem.  ( It would be better if you could do screen recording )

  5.**Capture App (please complete the following information):**

**p.s : If you don't know how to open a new issues report, you can directly use the above template to leave a comment below this article**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248804038120) by [Unito](https://www.unito.io)

**Comment by andous8** [comment]
Hi! I'm Jules. Thank you for giving me the opportunity to testing this app.
I don't know how to use Github, so please let me know if this kind of post is inappropriate.

Describe the bug
When I tapped the connect button after detecting the GoPro, the error in the attached image sometime occurred.
However, if I run it again, the fetching will complete even though there is the error.

To Reproduce:
Go to 'settings'
Tap 'GoPro'
Tap 'Scan for bluetooth devices'
Tap 'Connect' for detected GoPro

Screenshots
![snapshot Jules](https://user-images.githubusercontent.com/50861747/150779975-218305c8-34c8-4297-9f6f-f0da5e58270b.png)

Capture App :
- Device: iPhone7, GoPro Hero 10
- OS: iOS15.1

There are a few things I noticed. I hope this is helpful.
- I could get IPFS address, but I do not what this is and how to use.
- I tapped 'Share C2PA photo' but I could derive just a sentence, '#CaptureApp #OnlyTruePhotos'
- Uploading video files to the app is very time consuming and has a significant impact on the UX.
- Ideally, it would be nice to be able to upload from GoPro Cloud Data or GoPro Quik instead of directly from GoPro.

**Comment by ethanwu155** [comment]
Hi. Thanks for sharing your issue. Unfortunately this issue is no longer supported as it doesn't fall in line with the vision of Capture. We apologize for any inconveniences caused. Thanks for your time and if you have any other issues feel free to let us know.
