### ISSUE TITLE
Registration to blockchain 

### ISSUE THREAD

**Issue by cryptoguuy** [numbersprotocol/community-support#62]
Dear team,

recently am trying to register my captures around 25 photos, the registration of the photos takes a lot of time, it’s seems from the amount of data pair and transfer, but if I have to register all the photos I have to keep my mobile on all time in the main page of the capture app to complete all the photos.

my suggestion is, IF you can find away to complete the registration while the app On in RAM memory while the user doing different tasks on the mobile while the pictures are being registered. That’s will save a lot of time for the user and will not feel annoyed by waiting for the photos to be registered and saving the mobile battery.

actually now am waiting while the mobile display on for  30 mins and still the photos are not registered. While am using good net connection and let’s say new mobile. 

Thanks alot .

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248719065193) by [Unito](https://www.unito.io)

**Comment by tammyyang** [comment]
@scott-dt please help confirm if background uploading works.

**Comment by tammyyang** [comment]
@cryptoguuy The current upload process is already in the background. It will automatically start when you re-connect to the internet and there is no need to wait. You can even pause the upload and resume only when you feel the internet is strong enough. 

I would like to clarify if you are encountering "upload too slow" problem instead of "background uploading" (because background uploading should have been supported)?

Thank you for sharing the issue!

**Comment by ethanwu155** [comment]
Hi. Thanks for taking the time to share your issues. Our team has worked diligently to improve the registration performance of Capture Cam. We have also created a new Desktop application called Capture Dashboard that also provides users with another method to register via Upload. Each of these applications perform the background uploading. I encourage you to try it out and let us know your thoughts!

Appreciate your time and let us know if you have any more issues!
